name: "Build & Publish images"
on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run some checks
        run: |
          make test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Write origin cert info
        shell: bash
        run: |
          echo "$SECRET_ORIGIN_KEY" > ./client/cf-origin.key
          echo "$SECRET_ORIGIN_CERT" > ./client/cf-origin.crt
        env:
          SECRET_ORIGIN_CERT: "${{ secrets.ORIGIN_CERTIFICATE }}"
          SECRET_ORIGIN_KEY: "${{ secrets.ORIGIN_PRIVATE_KEY }}"

      - name: Build and push client
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: |
            ghcr.io/taiters/coup-client:latest
            ghcr.io/taiters/coup-client:${{ github.run_number }}

      - name: Build and push server
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: |
            ghcr.io/taiters/coup-server:latest
            ghcr.io/taiters/coup-server:${{ github.run_number }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SECRET_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SECRET_SERVER_IP >> ~/.ssh/known_hosts
        env:
          SECRET_SSH_KEY: "${{ secrets.SSH_KEY }}"
          SECRET_SERVER_IP: "${{ secrets.SERVER_IP }}"
      
      - name: Deploy
        run: |
          scp docker-compose.prod.yml $SECRET_SERVER_USER@$SECRET_SERVER_IP:~/docker-compose.yml
          ssh $SECRET_SERVER_USER@$SECRET_SERVER_IP "COUP_VERSION=${{ github.run_number }} docker compose up -d"
        env:
          SECRET_SERVER_USER: "${{ secrets.SERVER_USER }}"
          SECRET_SERVER_IP: "${{ secrets.SERVER_IP }}"